// Generated by delombok at Sat Jun 20 05:34:25 UTC 2020
package ds;

/** Hello world. */
public enum App {
  ;

  @SuppressWarnings("all")
  private static final java.util.logging.Logger LOGGER =
      java.util.logging.Logger.getLogger(App.class.getName());

  @SuppressWarnings("PMD.SystemPrintln")
  public static void main(String[] args) {
    System.out.println("Hello World!");
  }
}
